from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import pandas as pd
import traceback
import re

app = FastAPI(title="Klypto Strategy Evaluator API")

# ---------------------------------------------------------
# 1. Solid Data Validation (Pydantic Models)
# ---------------------------------------------------------
class CandleData(BaseModel):
    datetime: str
    open: float
    high: float
    low: float
    close: float
    volume: int

class StrategyPayload(BaseModel):
    symbol: str
    interval: str
    strategy: Optional[str] = "MACD_RSI"
    params: Optional[Dict[str, Any]] = {}
    strategy_code: Optional[str] = None
    historical_data: List[CandleData]


# ---------------------------------------------------------
# 2. Endpoints
# ---------------------------------------------------------
@app.get("/")
def read_root():
    return {"status": "FastAPI Strategy Engine is running", "message": "Welcome to Klypto Python Engine!"}

@app.post("/api/evaluate-strategy")
def evaluate_strategy(payload: StrategyPayload):
    try:
        # Convert incoming historical data to pandas DataFrame
        if not payload.historical_data:
            raise HTTPException(status_code=400, detail="historical_data cannot be empty")
        
        # We can convert list of Pydantic models to list of dicts directly
        data_dicts = [candle.model_dump() for candle in payload.historical_data]
        df = pd.DataFrame(data_dicts)
        
        # Ensure numerical columns are exact floats/ints for Pandas
        df['open'] = df['open'].astype(float)
        df['high'] = df['high'].astype(float)
        df['low'] = df['low'].astype(float)
        df['close'] = df['close'].astype(float)
        df['volume'] = df['volume'].astype(int)

        # ---------------------------------------------------------
        # --- Validate strategy_code content ---
        if payload.strategy_code:
            valid_keywords = ['plot_markers', 'markers.append', 'df[', 'df.loc', 'signal', 'plotshape', 'plot(']
            has_valid_code = any(kw in payload.strategy_code for kw in valid_keywords)
            if not has_valid_code or len(payload.strategy_code.strip()) < 20:
                raise HTTPException(
                    status_code=400, 
                    detail=f'Invalid strategy_code. Your code must contain valid strategy logic (e.g., use plot_markers, df[], signal etc.). Received: "{payload.strategy_code[:50]}"'
                )

        # 3. Dynamic Execution of Custom Strategy Code
        # ---------------------------------------------------------
        if payload.strategy_code:
            # --- SECURITY CHECK ---
            # Define forbidden patterns to prevent malicious code execution
            forbidden_patterns = [
                r"import\s+(os|sys|subprocess|shlex|socket|urllib|requests)",
                r"from\s+(os|sys|subprocess|shlex|socket|urllib|requests)\s+import",
                r"__import__",
                r"open\s*\(",
                r"eval\s*\(",
                r"exec\s*\(",
                r"globals\s*\(",
                r"locals\s*\(",
                r"os\.",
                r"sys\.",
                r"subprocess\."
            ]
            
            for pattern in forbidden_patterns:
                if re.search(pattern, payload.strategy_code):
                    raise HTTPException(
                        status_code=400, 
                        detail="Security Error: Unsafe code detected! System calls, file operations, and sensitive imports are not allowed."
                    )
            # ----------------------

            # Create a safe local scope for the exec function
            import numpy as np
            
            def wma(series, length):
                weights = np.arange(1, length + 1)
                return series.rolling(length).apply(lambda prices: np.dot(prices, weights) / weights.sum(), raw=True)

            local_scope = {
                'df': df, 
                'pd': pd, 
                'np': np, 
                'wma': wma,
                'open': df['open'],
                'high': df['high'],
                'low': df['low'],
                'close': df['close'],
                'volume': df['volume']
            }
            
            # Helper to handle plot functions generated by AI or users
            marker_count = [1]
            def plot_markers(data, *args, **kwargs):
                if isinstance(data, list):
                    # Handle list of dictionaries (like {"time": idx, "position": "...", "text": "..."})
                    df['text'] = None
                    df['position'] = None
                    df['signal'] = None
                    df['type'] = None
                    for m in data:
                        idx = m.get('time')
                        row_idx = None
                        if isinstance(idx, int) and 0 <= idx < len(df):
                            row_idx = idx
                        elif isinstance(idx, str):
                            matches = df.index[df['datetime'] == idx].tolist()
                            if matches:
                                row_idx = matches[0]
                                
                        if row_idx is not None:
                            df.at[row_idx, 'text'] = m.get('text')
                            df.at[row_idx, 'position'] = m.get('position')
                            df.at[row_idx, 'signal'] = m.get('signal', m.get('type'))
                            df.at[row_idx, 'type'] = m.get('type', m.get('signal'))
                else:
                    # Handle series/conditions
                    col_name = kwargs.get('title', kwargs.get('name', f"marker_{marker_count[0]}"))
                    df[col_name] = data
                    marker_count[0] += 1
                
            def plot(series_or_condition, *args, **kwargs):
                col_name = kwargs.get('title', kwargs.get('name', f"plot_{marker_count[0]}"))
                df[col_name] = series_or_condition
                marker_count[0] += 1

            local_scope['plot_markers'] = plot_markers
            local_scope['plot'] = plot
            local_scope['plotshape'] = plot_markers
            
            try:
                # The custom code should modify the 'df' directly
                # Pass local_scope as BOTH globals and locals so that
                # plot_markers, np, pd etc. are all accessible inside exec
                exec(payload.strategy_code, local_scope, local_scope)
                df = local_scope['df']
            except Exception as e:
                # Catch syntax or runtime errors in the user's python code
                error_trace = traceback.format_exc()
                print("Error executing custom strategy code:\n", error_trace)
                raise HTTPException(status_code=400, detail=f"Error in strategy code: {str(e)}")
        else:
            # Handle Built-in strategies (MACD_RSI, etc.)
            # For now, just add a dummy signal column if strategy_code is missing
            df['signal'] = 'HOLD'

        # Convert back to list of dicts for JSON response
        # Robustly replace NaN with None for JSON serialization
        raw_data = df.to_dict(orient='records')
        result_data = []
        for row in raw_data:
            clean_row = {}
            for k, v in row.items():
                if isinstance(v, float) and v != v:  # Check if v is NaN
                    clean_row[k] = None
                else:
                    clean_row[k] = v
            result_data.append(clean_row)
            
        return result_data

    except HTTPException as he:
        raise he
    except Exception as e:
        error_trace = traceback.format_exc()
        print("Internal Server Error:\n", error_trace)
        raise HTTPException(status_code=500, detail=f"Internal Server Error: {str(e)}")

@app.post("/api/scan-complete")
def scan_complete():
    print("\n" + "="*50)
    print(" 🚀 SCAN PROCESS COMPLETED SUCCESSFULLY! ")
    print("="*50 + "\n")
    return {"status": "Scan complete message logged."}

if __name__ == "__main__":
    import uvicorn
    # This block allows running with: python main.py
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
